[package]
name = "node-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
build_html = "2.4.0"
oneshot = "0.1.5"
serde_json = "1.0.96"
threadpool = "1.8.1"
